# Generated by Django 3.1.6 on 2021-02-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=70, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('due_date_to', models.DateTimeField(verbose_name='Срок исполнения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
